{"Name":"checking_uri_syntax","Result":false,"SerializedDocument":null,"DeserializedDocument":null,"Exception":"Traceback (most recent call last):\r\n  File \"C:\\Users\\Mat��\\bakalarka\\python-prov\\src\\main.py\", line 33, in <module>\r\n    class_.serialize(sys.argv[2])\r\n  File \"C:\\Users\\Mat��\\bakalarka\\python-prov\\src\\test_case.py\", line 18, in serialize\r\n    document.serialize(file_path, format=format_type, indent=2)\r\n  File \"C:\\Users\\Mat��\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\prov\\model.py\", line 2494, in serialize\r\n    serializer.serialize(stream, **args)\r\n  File \"C:\\Users\\Mat��\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\prov\\serializers\\provxml.py\", line 52, in serialize\r\n    xml_root = self.serialize_bundle(bundle=self.document, force_types=force_types)\r\n  File \"C:\\Users\\Mat��\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\prov\\serializers\\provxml.py\", line 110, in serialize_bundle\r\n    xml_bundle_root = etree.Element(_ns_prov(\"document\"), nsmap=nsmap)\r\n  File \"src\\lxml\\etree.pyx\", line 3042, in lxml.etree.Element\r\n  File \"src\\lxml\\apihelpers.pxi\", line 131, in lxml.etree._makeElement\r\n  File \"src\\lxml\\apihelpers.pxi\", line 118, in lxml.etree._makeElement\r\n  File \"src\\lxml\\apihelpers.pxi\", line 215, in lxml.etree._setNodeNamespaces\r\n  File \"src\\lxml\\apihelpers.pxi\", line 1775, in lxml.etree._uriValidOrRaise\r\nValueError: Invalid namespace URI 'http://www.w3. org/ns/prov#'","Description":"Python allows to create a document with invalid URI in memory. When registering namespace in Python, we use [ProvBundle#add_namespace()](https://github.com/trungdong/prov/blob/1cb710a26c623c5c706b1c6945c645efd9e925c0/src/prov/model.py#L1335) method, which just uses [NamespaceManager#add_namespace()](https://github.com/trungdong/prov/blob/master/src/prov/model.py#L1080) method and [Namespace constructor](https://github.com/trungdong/prov/blob/1cb710a26c623c5c706b1c6945c645efd9e925c0/src/prov/identifier.py#L85C9-L85C17) on line 1347:\r\n\r\n\\`return self._namespaces.add_namespace(Namespace(namespace_or_prefix, uri))\\`\r\n\r\nIn both Namespace constructor and NamespaceManager#add_namespace(), there is no validation of URI.\r\n\r\nWhen serializing XML format, Python uses the custom XML deserializer [ProvXMLSerializer](https://github.com/trungdong/prov/blob/master/src/prov/serializers/provxml.py#L34).\r\nWhen serializing namespaces in method [ProvXMLSerializer#serialize_bundle()](https://github.com/trungdong/prov/blob/master/src/prov/serializers/provxml.py#L70), it creates the nsmap on line 87, which is map containing all the namespaces.\r\nIn this method it creates the nsmap, which is map containing all the namespaces and then on line 110 uses [etree](https://lxml.de/tutorial.html) from [lxml](https://lxml.de/) library to create XML root element.\r\n\r\n\\`xml_bundle_root = etree.Element(_ns_prov(\"document\"), nsmap=nsmap)\\`\r\n\r\nBut in this method validation of URI takes place and it throws exception:  \\`ValueError: Invalid namespace URI 'http://www.w3. org/ns/prov#'\\`\r\n\r\n"}